[package]
edition = '2018'
name = 'liquidity-proxy'
version = '0.1.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.1", default-features = false, features = ["derive"] }
currencies = { version = "0.3.2", package = "orml-currencies", default-features = false }
tokens = { version = "0.3.2", package = "orml-tokens", default-features = false }
traits = { version = "0.3.2", package = "orml-traits", default-features = false }
frame-support = { version = "2.0.0", default-features = false }
frame-system = { version = "2.0.0", default-features = false }
pallet-balances = { version = "2.0.0", default-features = false }
sp-arithmetic = { version = "2.0.0", default-features = false }
sp-runtime = { version = "2.0.0", default-features = false }
sp-std = { version = "2.0.0", default-features = false }
common = { path = "../../common", default-features = false }
assets = { path = "../assets", default-features = false }
dex-manager = { path = "../dex-manager", default-features = false }
trading-pair = { path = "../trading-pair", default-features = false }
mock-liquidity-source = { path = "../mock-liquidity-source", default-features = false }

[dev-dependencies]
sp-core = { version = "2.0.0", default-features = false }
sp-io = { version = "2.0.0", default-features = false }
dex-api = { path = "../dex-api", default-features = false }
mock-liquidity-source = { path = "../mock-liquidity-source", default-features = false }
technical = { path = "../technical", default-features = false }
permissions = { path = "../permissions", default-features = false }

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'pallet-balances/std',
    'sp-arithmetic/std',
    'sp-runtime/std',
    'sp-std/std',
    'currencies/std',
    'tokens/std',
    'traits/std',
    'assets/std',
    'common/std',
    'dex-manager/std',
    'permissions/std',
    'trading-pair/std',
]
