[package]
edition = '2018'
authors = ['Polka Biome Ltd. <jihoon@tutanota.de>']
license = "BSD-4-Clause"
homepage = 'https://sora.org'
repository = 'https://github.com/sora-xor/sora2-network'
name = 'liquidity-proxy'
version = '0.1.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = "parity-scale-codec", version = "2", default-features = false, features = ["derive"] }
currencies = { version = "0.4", package = "orml-currencies", default-features = false }
tokens = { version = "0.4", package = "orml-tokens", default-features = false }
traits = { version = "0.4", package = "orml-traits", default-features = false }
frame-support = { version = "3", default-features = false }
frame-system = { version = "3", default-features = false }
pallet-balances = { version = "3", default-features = false }
sp-arithmetic = { version = "3", default-features = false }
sp-runtime = { version = "3", default-features = false }
sp-std = { version = "3", default-features = false }
common = { path = "../../common", default-features = false }
assets = { path = "../assets", default-features = false }
trading-pair = { path = "../trading-pair", default-features = false }
pallet-timestamp = { version = "3", default-features = false }

[dev-dependencies]
ceres-liquidity-locker = { path = "../ceres-liquidity-locker", default-features = false }
demeter-farming-platform = { path = "../demeter-farming-platform", default-features = false }
serde = { version = "1.0.101", default-features = false, features = ["derive"] }
sp-core = { version = "3", default-features = false }
sp-io = { version = "3", default-features = false }
common = { path = "../../common", features = ["test"] }
dex-api = { path = "../dex-api" }
dex-manager = { path = "../dex-manager" }
mock-liquidity-source = { path = "../mock-liquidity-source" }
technical = { path = "../technical" }
permissions = { path = "../permissions" }
vested-rewards = { path = "../vested-rewards" }
pool-xyk = { path = "../pool-xyk" }
pswap-distribution = { path = "../pswap-distribution" }
multicollateral-bonding-curve-pool = { path = "../multicollateral-bonding-curve-pool" }


[features]
default = ['std']
std = [
    'codec/std',
    'currencies/std',
    'frame-support/std',
    'frame-system/std',
    'pallet-balances/std',
    'sp-arithmetic/std',
    'sp-runtime/std',
    'sp-std/std',
    'tokens/std',
    'traits/std',
    'trading-pair/std',
]
