[package]
description = 'Pallet for automatic distribution of pswap tokens for liquidity providers.'
authors = ['Polka Biome Ltd. <jihoon@tutanota.de>']
license = "BSD-4-Clause"
homepage = 'https://sora.org'
repository = 'https://github.com/sora-xor/sora2-network'
version = '0.1.0'
name = 'pswap-distribution-benchmarking'
edition = '2021'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = [
    "derive",
] }
scale-info = { version = "2", default-features = false, features = ["derive"] }
frame-benchmarking = { workspace = true, default-features = false, optional = true }
frame-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }
hex-literal = { version = "0.4.1" }
sp-core = { workspace = true, default-features = false }
sp-io = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }
tokens = { workspace = true, default-features = false }
traits = { workspace = true, default-features = false }

assets = { path = "../../assets", default-features = false }
common = { path = "../../../common", default-features = false }
permissions = { path = "../../permissions", default-features = false }
pool-xyk = { path = "../../pool-xyk", default-features = false }
pswap-distribution = { path = "..", default-features = false }
technical = { path = "../../technical", default-features = false }
trading-pair = { path = "../../trading-pair", default-features = false }
pallet-timestamp = { workspace = true, default-features = false }

[dev-dependencies]
ceres-liquidity-locker = { path = "../../ceres-liquidity-locker", default-features = false }
currencies = { workspace = true }
demeter-farming-platform = { path = "../../demeter-farming-platform", default-features = false }
hex-literal = { version = '0.4.1' }
pallet-balances = { workspace = true }
serde = { version = "1.0.101", features = ["derive"] }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

common = { path = "../../../common", features = ["test"] }
dex-manager = { path = "../../dex-manager" }
trading-pair = { path = "../../trading-pair" }

[features]
default = ["std"]

std = [
    "assets/std",
    "frame-benchmarking/std",
    "frame-support/std",
    "frame-system/std",
    "permissions/std",
    "pool-xyk/std",
    "pswap-distribution/std",
    "sp-std/std",
    "tokens/std",
    "traits/std",
]

runtime-benchmarks = [
    "frame-benchmarking",
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
]
