[package]
edition = "2021"
authors = ['Polka Biome Ltd. <jihoon@tutanota.de>']
license = "BSD-4-Clause"
description = 'Pallet for aggregation of available oracle sources for other pallets and external api'
name = "oracle-proxy"
version = "1.0.0"
homepage = 'https://sora.org'
repository = 'https://github.com/sora-xor/sora2-network'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
frame-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }
frame-benchmarking = { workspace = true, default-features = false, optional = true }
common = { path = "../../common", default-features = false }
sp-std = { workspace = true, default-features = false }
codec = { package = "parity-scale-codec", version = "3", default-features = false }
scale-info = { version = "2", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true, features = [
    "derive",
], default-features = false }
sp-io = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }
sp-core = { workspace = true, default-features = false }

[dev-dependencies]
hex-literal = "0.4.1"
pallet-balances = { workspace = true, default-features = false }
band = { path = "../band", default-features = false }
pallet-timestamp = { workspace = true, default-features = false }

[features]
default = ['std']
std = [
    "frame-support/std",
    "frame-system/std",
    "frame-benchmarking/std",
    "band/std",
    "common/std",
    "sp-std/std",
    "codec/std",
    "scale-info/std",
    "codec/std",
    "sp-io/std",
    "sp-runtime/std",
    "sp-core/std",
]
runtime-benchmarks = [
    "frame-benchmarking",
    "frame-system/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
]

try-runtime = ["frame-support/try-runtime"]
