[package]
name = "framenode-chain-spec"
version = "3.6.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3", features = [
    "derive",
    "chain-error",
] }
frame-support = { workspace = true }
hex-literal = { workspace = true }
sc-consensus-grandpa = { workspace = true }
# sc-finality-grandpa = { workspace = true, package = "finality-grandpa" }
sc-network = { workspace = true }
sc-network-common = { workspace = true }
sc-service = { workspace = true }
sp-consensus-aura = { workspace = true }
sp-consensus-babe = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

bridge-multisig = { workspace = true, default-features = false }

# bridge-multisig = { git = "https://github.com/soramitsu/sora2-frame-pallets.git", branch = "polkadot-v1.1.0", package = "pallet-multisig" }

common = { path = "../../common" }
faucet = { path = "../../pallets/faucet", optional = true }
framenode-runtime = { path = "../../runtime" }
iroha-migration = { path = "../../pallets/iroha-migration" }
permissions = { path = "../../pallets/permissions" }
rewards = { path = "../../pallets/rewards" }
technical = { path = "../../pallets/technical" }
xor-fee = { path = "../../pallets/xor-fee" }

[dev-dependencies]
common = { path = "../../common", features = ["test"] }

[features]
include-real-files = []
main-net-coded = []
test = ["common/test"]
# test = []


private-net = ["faucet", "framenode-runtime/private-net"]
# private-net = []
wip = ["framenode-runtime/wip"]
# wip = []
# ready-to-test = []
stage = ["framenode-runtime/stage"]
runtime-benchmarks = []
