[package]
edition = '2018'
name = 'token-dealer-benchmarking'
version = '0.1.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.1", default-features = false, features = ["derive"] }
frame-benchmarking = { version = "2.0.0", default-features = false }
frame-support = { version = "2.0.0", default-features = false }
frame-system = { version = "2.0.0", default-features = false }
sp-std = { version = "2.0.0", default-features = false }
hex-literal = { version = "0.3.1" }

[dev-dependencies]
sp-runtime = { version = "2.0.0", default-features = false }
sp-core = { version = "2.0.0", default-features = false }
sp-io = { version = "2.0.0", default-features = false }
common = { path = "../../../common", default-features = false }
pallet-balances = { version = "2.0.0", default-features = false }
parachain-info = { path = "../../parachain-info", default-features = false}
#cumulus-message-broker = { git = "https://github.com/paritytech/cumulus",  default-features = false, rev = '9512520b95ef2272d2f0b56097eb2805097bef81' }


[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'frame-benchmarking/std',
    'sp-std/std',
    'cumulus-token-dealer/std',
]
