[package]
name = "iroha-migration-rpc"
version = "0.1.0"
edition = "2021"
authors = ['Polka Biome Ltd. <jihoon@tutanota.de>']
license = "BSD-4-Clause"
homepage = 'https://sora.org'
repository = 'https://github.com/sora-xor/sora2-network'

[dependencies]
jsonrpsee = { version = "0.16.2", features = ["server", "macros"] }
sp-runtime = { workspace = true }
sp-api = { workspace = true }
sp-blockchain = { workspace = true }
sp-rpc = { workspace = true }

# Path dependencies
iroha-migration-runtime-api = { path = "../runtime-api" }
