[package]
name = "remote-ext"
version = "0.1.0"
edition = "2021"
authors = ["Polka Biome Ltd. <jihoon@tutanota.de>"]
license = "BSD-4-Clause"
homepage = "https://sora.org"
repository = "https://github.com/sora-xor/sora2-network"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" }
clap = { workspace = true, features = ["derive"] }
jsonrpsee = { workspace = true, features = ["ws-client", "macros"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync"] }
anyhow = { workspace = true }
env_logger = { workspace = true }
hex = { workspace = true }

frame-remote-externalities = { workspace = true }

sp-core = { workspace = true }
sp-version = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }

frame-system = { workspace = true }
frame-support = { workspace = true }
frame-election-provider-support = { workspace = true }

framenode-runtime = { path = "../../runtime", default-features = false, features = [
    "std",
] }

liquidity-proxy = { path = "../../pallets/liquidity-proxy" }
common = { path = "../../common" }
