[package]
name = "remote-ext"
version = "0.1.0"
edition = "2021"
authors = ["Polka Biome Ltd. <jihoon@tutanota.de>"]
license = "BSD-4-Clause"
homepage = "https://sora.org"
repository = "https://github.com/sora-xor/sora2-network"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" }
clap = { version = "=4.3.17", features = ["derive"] }
jsonrpsee = { version = "0.16.2", features = ["ws-client", "macros"] }
log = "0.4.17"
serde = "1.0.137"
serde_json = "1.0"
thiserror = "1.0.31"
tokio = { version = "1.18.2", features = ["macros", "rt-multi-thread", "sync"] }
anyhow = "1.0.51"
hex = "0.4.3"
env_logger = "0.9.0"

frame-remote-externalities = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38" }

sp-core = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38" }
sp-version = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38" }
sp-io = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38" }
sp-runtime = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38" }

frame-system = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38" }
frame-support = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38" }
frame-election-provider-support = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38" }

framenode-runtime = { path = "../../runtime", default-features = false, features = [
    "std",
] }

liquidity-proxy = { path = "../../pallets/liquidity-proxy" }
dex-manager = { path = "../../pallets/dex-manager" }
xst = { path = "../../pallets/xst" }
common = { path = "../../common" }

[features]
ready-to-test = [
    "common/ready-to-test",
    "liquidity-proxy/ready-to-test",
    "framenode-runtime/ready-to-test",
]
