[patch.crates-io]
jsonrpc-core = { git = "https://github.com/soramitsu/jsonrpc.git", branch = "new_fragment_capacity" }
jsonrpc-ws-server = { git = "https://github.com/soramitsu/jsonrpc.git", branch = "new_fragment_capacity" }
jsonrpc-server-utils = { git = "https://github.com/soramitsu/jsonrpc.git", branch = "new_fragment_capacity" }

[workspace]
members = [
    "runtime/",
    "common",
    "pallets/assets",
    "pallets/permissions",
    "pallets/trading-pair",
    "pallets/dex-manager",
    "pallets/dex-api",
    "pallets/farming",
    "pallets/faucet",
    "pallets/iroha-migration",
    "pallets/liquidity-proxy",
    "pallets/mock-liquidity-source",
    "pallets/technical",
    "pallets/pool-xyk",
    "pallets/xor-fee",
    "pallets/referral-system",
    "pallets/bonding-curve-pool",
    "pallets/eth-bridge",
    "pallets/pswap-distribution",
    "node/",
]

[profile.release]
panic = 'unwind'
