[package]
name = "substrate-gen"
version = "0.1.0"
edition = "2021"

[build-dependencies]
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = [
    "derive",
    "chain-error",
] }
scale-info = { version = "2", default-features = false, features = ["derive"] }
framenode-runtime = { path = "../../runtime", default-features = false, features = [
    "std",
    "private-net",
] }
hex = "0.4.3"
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.25", default-features = false }

[dependencies]
common = { path = "../../common" }
subxt = { git = "https://github.com/sora-xor/subxt", branch = "polkadot-v0.9.25" }
codec = { package = "parity-scale-codec", version = "3", features = ["derive"] }
scale-info = { version = "2", features = ["derive"] }
bridge-types = { path = "../../pallets/trustless-eth-bridge/types" }
beefy-primitives = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.25" }
jsonrpsee = { version = "0.14", features = [
    "macros",
    "ws-client",
    "http-client",
] }
async-trait = "0.1.49"
serde = { version = "1.0.137", features = ["derive"] }
