[package]
name = "contract-extrinsics"
authors = ["Soramitsu"]
license = "BSD-4-Clause"
homepage = "https://sora.org"
repository = 'https://github.com/sora-xor/sora2-network'
version = "0.1.0"
edition = "2021"

[dependencies]
# TODO Update versions
ink = { version = "5.0.0", default-features = false}
#scale-info = { version = "2", default-features = false, features = ["derive"] }
#scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }

frame-support = { git = "https://github.com/sora-xor/polkadot-sdk.git", branch = "add_sora_substrate_commits", default-features = false }
sp-std = { git = "https://github.com/sora-xor/polkadot-sdk.git", branch = "add_sora_substrate_commits", default-features = false }
sp-core = { git = "https://github.com/sora-xor/polkadot-sdk.git", branch = "add_sora_substrate_commits", default-features = false }
rustc-hex = "2.1.0"
serde = { version = "1.0", features = ["derive"], default-features = false }
#orml-currencies = { git = "https://github.com/open-web3-stack/open-runtime-module-library.git", package = "orml-currencies", default-features = false }

#common = { path = "../common", default-features = false }
#order-book = { path="../pallets/order-book" }

[features]
default = ["std"]

std = [
#    "sp-core/std",
    "frame-support/std",
#    "sp-std/std",
#    "serde/std"
#    "common/std"
]
