[package]
name = "contract-extrinsics"
version = "4.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# TODO Update versions
scale-info = { version = "2", default-features = false, features = ["derive"] }
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
ink_primitives = "4.2.1"

frame-support = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
sp-std = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }

common = { path = "../common", default-features = false }
order-book = {path="../pallets/order-book", default-features = false}

[features]
std = [
    "common/std",
    "scale-info/std",
    "ink_primitives/std",
    "frame-support/std",
    "sp-std/std",
]
