[package]
name = "contract-extrinsics"
authors = ["Soramitsu"]
license = "BSD-4-Clause"
homepage = "https://sora.org"
repository = 'https://github.com/sora-xor/sora2-network'
version = "0.1.0"
edition = "2021"

[dependencies]
# TODO Update versions
scale-info = { version = "2", default-features = false, features = ["derive"] }
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }

frame-support = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
sp-std = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }

common = { path = "../common", default-features = false }
order-book = {path="../pallets/order-book", default-features = false}

[features]
std = [
    "common/std",
    "scale-info/std",
    "frame-support/std",
    "sp-std/std",
]
