[package]
edition = '2018'
name = 'framenode-runtime'
version = '0.1.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
wasm-builder-runner = { package = 'substrate-wasm-builder-runner', version = '2.0.0' }

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.1", default-features = false, features = ["derive"] }
hex-literal = { version = '0.3.1' }
serde = { features = ['derive'], optional = true, version = '1.0.101' }
common = { path = "../common", default-features = false }
faucet = { path = "../pallets/faucet", default-features = false }
assets = { path = "../pallets/assets", default-features = false }
bonding-curve-pool = { path = "../pallets/bonding-curve-pool", default-features = false }
dex-api = { path = "../pallets/dex-api", default-features = false }
dex-manager = { path = "../pallets/dex-manager", default-features = false }
farming = { path = "../pallets/farming", default-features = false}
liquidity-proxy = { path = "../pallets/liquidity-proxy", default-features = false}
mock-liquidity-source = { path = "../pallets/mock-liquidity-source", default-features = false}
permissions = { path = "../pallets/permissions", default-features = false}
pool-xyk = { path = "../pallets/pool-xyk", default-features = false}
referral-system = { path = "../pallets/referral-system", default-features = false}
technical = { path = "../pallets/technical", default-features = false}
trading-pair = { path = "../pallets/trading-pair", default-features = false}
xor-fee = { path = "../pallets/xor-fee", default-features = false}
dex-runtime-api = { path = "../pallets/dex-api/runtime-api", default-features = false}
dex-manager-runtime-api = { path = "../pallets/dex-manager/runtime-api", default-features = false}
trading-pair-runtime-api = { path = "../pallets/trading-pair/runtime-api", default-features = false}
assets-runtime-api = { path = "../pallets/assets/runtime-api", default-features = false}
liquidity-proxy-runtime-api = { path = "../pallets/liquidity-proxy/runtime-api", default-features = false}


# Substrate dependencies
frame-benchmarking = { default-features = false, optional = true, version = '2.0.0' }
frame-executive = { default-features = false, version = '2.0.0' }
frame-support = { default-features = false, version = '2.0.0' }
frame-system = { default-features = false, version = '2.0.0' }
frame-system-benchmarking = { default-features = false, optional = true, version = '2.0.0' }
frame-system-rpc-runtime-api = { default-features = false, version = '2.0.0' }
pallet-aura = { default-features = false, version = '2.0.0' }
pallet-balances = { default-features = false, version = '2.0.0' }
pallet-grandpa = { default-features = false, version = '2.0.0' }
pallet-babe = { default-features = false, version = '2.0.0' }
pallet-randomness-collective-flip = { default-features = false, version = '2.0.0' }
pallet-sudo = { default-features = false, version = '2.0.0' }
pallet-timestamp = { default-features = false, version = '2.0.0' }
pallet-contracts = { default-features = false, version = '2.0.0' }
#pallet-session = { default-features = false, version = '2.0.0' }
pallet-session = { default-features = false, features = ["historical"], version = '2.0.0' }
pallet-staking = { git = "https://github.com/soramitsu/sora2-frame-pallets", default-features = false, branch = "selected-v2.0.0"}
pallet-transaction-payment = { git = "https://github.com/soramitsu/sora2-frame-pallets", default-features = false, branch = "selected-v2.0.0"}
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/soramitsu/sora2-frame-pallets", default-features = false, branch = "selected-v2.0.0"}

sp-api = { default-features = false, version = '2.0.0' }
sp-block-builder = { default-features = false, version = '2.0.0' }
sp-consensus-aura = { default-features = false, version = '0.8.0' }
sp-consensus-babe = { default-features = false, version = '0.8.0' }
sp-core = { default-features = false, version = '2.0.0' }
sp-inherents = { default-features = false, version = '2.0.0' }
sp-offchain = { default-features = false, version = '2.0.0' }
sp-runtime = { default-features = false, version = '2.0.0' }
sp-session = { default-features = false, version = '2.0.0' }
sp-std = { default-features = false, version = '2.0.0' }
sp-transaction-pool = { default-features = false, version = '2.0.0' }
sp-version = { default-features = false, version = '2.0.0' }

sp-staking = { default-features = false, version = '2.0.0' }
pallet-authorship = { default-features = false, version = '2.0.0' }

# Other
currencies = { version = "0.3.2", package = "orml-currencies", default-features = false }
tokens = { version = "0.3.2", package = "orml-tokens", default-features = false }

static_assertions = "1.1.0"

[features]
default = ['std']
runtime-benchmarks = [
    'frame-benchmarking',
    'frame-support/runtime-benchmarks',
    'frame-system-benchmarking',
    'frame-system/runtime-benchmarks',
    'pallet-balances/runtime-benchmarks',
    'pallet-timestamp/runtime-benchmarks',
    'sp-runtime/runtime-benchmarks',
]
std = [
    'codec/std',
    'serde',
    'frame-executive/std',
    'frame-support/std',
    'frame-system/std',
    'frame-system-rpc-runtime-api/std',
    'pallet-aura/std',
    'pallet-babe/std',
    'pallet-balances/std',
    'pallet-grandpa/std',
    'pallet-randomness-collective-flip/std',
    'pallet-sudo/std',
    'pallet-timestamp/std',
    'pallet-transaction-payment/std',
    'pallet-transaction-payment-rpc-runtime-api/std',
    'pallet-contracts/std',
    'pallet-session/std',
    'pallet-staking/std',
    'sp-api/std',
    'sp-block-builder/std',
    'sp-consensus-aura/std',
    'sp-consensus-babe/std',
    'sp-core/std',
    'sp-inherents/std',
    'sp-offchain/std',
    'sp-runtime/std',
    'sp-session/std',
    'sp-std/std',
    'sp-transaction-pool/std',
    'sp-version/std',
    'permissions/std',
    'faucet/std',
    'assets/std',
    'dex-manager/std',
    'sp-staking/std',
    'pallet-authorship/std',
]
