[package]
name = "order-book-benchmarking"
authors = ["Soramitsu"]
license = "BSD-4-Clause"
homepage = "https://sora.org"
repository = 'https://github.com/sora-xor/sora2-network'
edition = "2021"
version = "0.1.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = [
    "derive",
] }
scale-info = { version = "2", default-features = false, features = ["derive"] }
sp-runtime = { git = "https://github.com/sora-xor/polkadot-sdk.git", branch = "polkadot-v1.1.0", default-features = false }
sp-std = { git = "https://github.com/sora-xor/polkadot-sdk.git", branch = "polkadot-v1.1.0", default-features = false }
frame-benchmarking = { git = "https://github.com/sora-xor/polkadot-sdk.git", branch = "polkadot-v1.1.0", default-features = false, optional = true }
frame-support = { git = "https://github.com/sora-xor/polkadot-sdk.git", branch = "polkadot-v1.1.0", default-features = false }
frame-system = { git = "https://github.com/sora-xor/polkadot-sdk.git", branch = "polkadot-v1.1.0", default-features = false }
assets = { path = "../../assets", default-features = false }
common = { path = "../../../common", default-features = false }
order-book = { path = "..", default-features = false }
trading-pair = { path = "../../trading-pair", default-features = false }
log = "0.4.20"

[dev-dependencies]
sp-core = { git = "https://github.com/sora-xor/polkadot-sdk.git", branch = "polkadot-v1.1.0", default-features = false }
sp-io = { git = "https://github.com/sora-xor/polkadot-sdk.git", branch = "polkadot-v1.1.0", default-features = false }
framenode-chain-spec = { path = "../../../node/chain_spec", features = ["test"] }
framenode-runtime = { path = "../../../runtime", default-features = false, features = [
    "std",
] }
pallet-balances = { git = "https://github.com/sora-xor/polkadot-sdk.git", branch = "polkadot-v1.1.0" }
pallet-collective = { git = "https://github.com/sora-xor/polkadot-sdk.git", branch = "polkadot-v1.1.0", default-features = false }
pallet-timestamp = { git = "https://github.com/sora-xor/polkadot-sdk.git", branch = "polkadot-v1.1.0", default-features = false }
log = "0.4.20"

[features]
default = ["std"]
std = [
    "assets/std",
    "common/std",
    "frame-support/std",
    "frame-system/std",
    "order-book/std",
    "pallet-timestamp/std",
    "scale-info/std",
    "sp-runtime/std",
    "scale-info/std",
    "sp-std/std",
    "trading-pair/std",
]

runtime-benchmarks = [
    "frame-benchmarking",
    "frame-system/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
    "order-book/runtime-benchmarks",
    "common/runtime-benchmarks"
]

try-runtime = ["frame-support/try-runtime", "order-book/try-runtime"]
