[package]
authors = ['Polka Biome Ltd. <jihoon@tutanota.de>']
license = "BSD-4-Clause"
homepage = 'https://sora.org'
repository = 'https://github.com/sora-xor/sora2-network'
description = 'Pallet for claiming rewards'
edition = '2021'
name = 'rewards'
version = '1.3.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = [
    "derive",
] }
log = { workspace = true }
scale-info = { workspace = true, default-features = false, features = ["derive"] }
frame-benchmarking = { workspace = true, default-features = false, optional = true }
frame-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }
hex-literal = { workspace = true, default-features = false }
secp256k1 = { version = "0.7", features = [
    "hmac",
    "static-context",
], default-features = false, package = "libsecp256k1" }
serde = { workspace = true, features = ["derive"], default-features = false }
sp-core = { workspace = true, default-features = false }
sp-io = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }
orml-traits = { workspace = true, default-features = false }

common = { path = "../../common", default-features = false }
technical = { path = "../technical", default-features = false }

[dev-dependencies]
currencies = { workspace = true }
pallet-balances = { workspace = true }
sp-runtime = { workspace = true }
tokens = { workspace = true }

assets = { path = "../assets" }
common = { path = "../../common", features = ["test"] }
permissions = { path = "../permissions" }
technical = { path = "../technical" }

[features]
default = ['std']

std = [
    'codec/std',
    "scale-info/std",
    'frame-support/std',
    'frame-system/std',
    'frame-benchmarking/std',
    'serde/std',
    'sp-core/std',
    'sp-io/std',
    'sp-std/std',
    'secp256k1/std',
    'common/std',
]

runtime-benchmarks = [
    "frame-benchmarking",
    "frame-system/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
]

try-runtime = ["frame-support/try-runtime"]

include-real-files = []
