[package]
authors = ["Polka Biome Ltd. <jihoon@tutanota.de>"]
license = "BSD-4-Clause"
homepage = "https://sora.org"
repository = "https://github.com/sora-xor/sora2-network"
description = "FRAME pallet template for defining custom runtime logic."
edition = "2021"
name = "xor-fee"
version = "0.1.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = [
    "derive",
] }
log = { workspace = true }
scale-info = { workspace = true, default-features = false, features = ["derive"] }
frame-benchmarking = { workspace = true, default-features = false, optional = true }
frame-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }
pallet-session = { workspace = true, default-features = false, features = [
    "historical",
] }
pallet-transaction-payment = { workspace = true, default-features = false }
serde = { workspace = true, features = ["derive"], optional = true }
sp-arithmetic = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }
sp-staking = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }
sp-core = { workspace = true, default-features = false }
traits = { workspace = true, default-features = false }
smallvec = { workspace = true }
common = { path = "../../common", default-features = false }

[dev-dependencies]
currencies = { workspace = true }
pallet-balances = { workspace = true }
pallet-timestamp = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }
tokens = { workspace = true }
assets = { path = "../assets" }
common = { path = "../../common", features = ["test"] }
permissions = { path = "../permissions" }

[features]
default = ["std"]

std = [
    "codec/std",
    "scale-info/std",
    "frame-support/std",
    "frame-system/std",
    "frame-benchmarking/std",
    "pallet-session/std",
    "pallet-transaction-payment/std",
    "sp-arithmetic/std",
    "sp-runtime/std",
    "sp-staking/std",
    "sp-std/std",
    "sp-core/std",
    "traits/std",
    "assets/std",
    "common/std",
]

runtime-benchmarks = [
    "frame-benchmarking",
    "frame-system/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
]

try-runtime = [
    "frame-support/try-runtime",
]

wip = []
