[package]
authors = ["Polka Biome Ltd. <jihoon@tutanota.de>"]
license = "BSD-4-Clause"
homepage = "https://sora.org"
repository = "https://github.com/sora-xor/sora2-network"
description = "FRAME pallet template for defining custom runtime logic."
edition = "2021"
name = "xor-fee"
version = "0.1.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = [
    "derive",
] }
scale-info = { version = "2", default-features = false, features = ["derive"] }
frame-benchmarking = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.25", default-features = false, optional = true }
frame-support = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.25", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.25", default-features = false }
pallet-session = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.25", default-features = false }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.25", default-features = false }
serde = { version = "1.0.101", features = ["derive"], optional = true }
sp-arithmetic = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.25", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.25", default-features = false }
sp-staking = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.25", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.25", default-features = false }
traits = { git = "https://github.com/open-web3-stack/open-runtime-module-library.git", package = "orml-traits", default-features = false }
smallvec = "1.5.0"
assets = { path = "../assets", default-features = false }
common = { path = "../../common", default-features = false }
liquidity-proxy = { path = "../liquidity-proxy", default-features = false }

eth-bridge = { path = "../eth-bridge", default-features = false }
referrals = { path = "../referrals", default-features = false }

pallet-staking = { git = "https://github.com/soramitsu/sora2-frame-pallets.git", branch = "polkadot-v0.9.25-lock-fix", default-features = false, optional = true }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.25", default-features = false, optional = true }
permissions = { path = "../permissions", default-features = false, optional = true }
pool-xyk = { path = "../pool-xyk", default-features = false, optional = true }
trading-pair = { path = "../trading-pair", default-features = false, optional = true }

[dev-dependencies]
currencies = { git = "https://github.com/open-web3-stack/open-runtime-module-library.git", package = "orml-currencies" }
pallet-balances = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.25" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.25" }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.25" }
sp-io = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.25" }
tokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library.git", package = "orml-tokens" }
pallet-staking = { git = "https://github.com/soramitsu/sora2-frame-pallets.git", branch = "polkadot-v0.9.25-lock-fix" }
bridge-multisig = { git = "https://github.com/soramitsu/sora2-frame-pallets.git", branch = "polkadot-v0.9.25-lock-fix", package = "pallet-multisig" }
pallet-scheduler = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.25" }
frame-election-provider-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.25" }

common = { path = "../../common", features = ["test"] }
ceres-liquidity-locker = { path = "../ceres-liquidity-locker" }
demeter-farming-platform = { path = "../demeter-farming-platform" }
dex-manager = { path = "../dex-manager" }
mock-liquidity-source = { path = "../mock-liquidity-source" }
permissions = { path = "../permissions" }
pswap-distribution = { path = "../pswap-distribution" }
pool-xyk = { path = "../pool-xyk" }
technical = { path = "../technical" }
trading-pair = { path = "../trading-pair" }

[features]
default = ["std"]

std = [
    "codec/std",
    "scale-info/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-session/std",
    "pallet-transaction-payment/std",
    "serde/std",
    "sp-arithmetic/std",
    "sp-runtime/std",
    "sp-staking/std",
    "sp-std/std",
    "traits/std",
    "assets/std",
    "common/std",
    "liquidity-proxy/std",

    "eth-bridge/std",
    "referrals/std",

    "pallet-staking?/std",
    "sp-core?/std",
    "permissions?/std",
    "pool-xyk?/std",
    "trading-pair?/std"
]

runtime-benchmarks = [
    "frame-benchmarking",
    "frame-system/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
    "pallet-staking",
    "sp-core",
    "permissions",
    "pool-xyk",
    "trading-pair"
]
