version: "3.5"
name: sora2-substrate

services:
  geth:
    image: geth:local
    container_name: bridge-geth
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile.geth
    healthcheck:
      test: "geth attach --exec eth.blockNumber ws://localhost:8545 || exit 1"
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    entrypoint: sh
    command: /configs/run_geth.sh
    ports:
      - 8545:8545
    volumes:
      - geth-data:/data
    networks:
      - bridgenet


  hardhat:
    image: hardhat:local
    build: 
      context: ..
      dockerfile: bridge-docker/Dockerfile.hardhat
    container_name: bridge-hardhat
    entrypoint: sh
    command: docker-deploy.sh
    depends_on:
      geth:
        condition: service_healthy
    volumes:
      - hardhat-data:/data
    networks:
      - bridgenet

  register-bridge:
    image: sora2/substrate-local
    container_name: bridge-register-bridge
    build:
      context: ..
      dockerfile: bridge-docker/Dockerfile.sora
    environment:
      - RUST_LOG=info,relayer=debug
    depends_on:
      hardhat:
        condition: service_started
      sora-alice:
        condition: service_started
    entrypoint: sh
    command: /register-bridge/register-bridge.sh
    volumes:
      - hardhat-data:/data
      - ./register-bridge:/register-bridge
    networks:
      - bridgenet

  relay-substrate:
    image: sora2/substrate-local
    container_name: bridge-relay-substrate
    restart: always
    build:
      context: ..
      dockerfile: bridge-docker/Dockerfile.sora
    environment:
      - RUST_LOG=info,relayer=debug
    depends_on:
      register-bridge:
        condition: service_completed_successfully
    command: ["relayer",
        "--ethereum-url", "ws://bridge-geth:8545",
        "--substrate-url", "ws://bridge-sora-alice:9944",
        "--ethereum-key", "3b61c8157aea9aba36248468af274cac4163b0b58c63eb66a8d2bbf219906c62",
        "bridge", "relay", "evm", "sora"
      ]
    networks:
      - bridgenet

  relay-ethereum:
    image: sora2/substrate-local
    container_name: bridge-relay-ethereum
    restart: always
    build:
      context: ..
      dockerfile: bridge-docker/Dockerfile.sora
    environment:
      - RUST_LOG=info,relayer=debug
    depends_on:
      register-bridge:
        condition: service_completed_successfully
    command: ["relayer",
        "--ethereum-url", "ws://bridge-geth:8545",
        "--substrate-url", "ws://bridge-sora-alice:9944",
        "--substrate-key", "//Relayer",
        "bridge", "relay", "sora", "evm",
        "--base-path", "/data"
      ]
    volumes:
      - relay-ethereum-data:/data
    networks:
      - bridgenet

  redis:
    image: 'redis:alpine'
    container_name: bridge-redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server
    volumes:
      - redis-data:/data
    networks:
      - bridgenet

  postgres:
    image: postgres:14
    container_name: bridge-postgres
    restart: always
    command: postgres -c 'max_connections=250'
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - bridgenet
  
  pgweb:
    restart: always  
    image: sosedoff/pgweb
    container_name: bridge-pgweb
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@bridge-postgres:5432/postgres?sslmode=disable
    depends_on:
      - postgres
    networks:
      - bridgenet

  blockscout:
    depends_on:
      postgres:
        condition: service_started
      smart-contract-verifier:
        condition: service_started
      redis:
        condition: service_started
      geth:
        condition: service_healthy
    image: blockscout/blockscout:${DOCKER_TAG:-latest}
    container_name: bridge-blockscout
    restart: always
    command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    env_file:
      -  ./envs/common-blockscout.env
    environment:
        ETHEREUM_JSONRPC_VARIANT: 'geth'
        BLOCK_TRANSFORMER: 'base'
        ETHEREUM_JSONRPC_HTTP_URL: http://bridge-geth:8545/
        DATABASE_URL: postgresql://postgres:@bridge-postgres:5432/postgres?ssl=false
        ECTO_USE_SSL: 'false'
        SECRET_KEY_BASE: '56NtB48ear7+wMSf0IQuWDAAazhpb31qyc7GiyspBP2vh7t5zlCsF5QDv76chXeN'
    ports:
      - 4000:4000
    networks:
      - bridgenet

  smart-contract-verifier:
    image: ghcr.io/blockscout/smart-contract-verifier:${SMART_CONTRACT_VERIFIER_DOCKER_TAG:-latest}
    container_name: bridge-verifier
    restart: always
    env_file:
      -  ./envs/common-smart-contract-verifier.env
    ports:
      - 8043:8043
    networks:
      - bridgenet
volumes:
  postgres-data: null
  redis-data: null
  geth-data: null
  hardhat-data: null
  relay-ethereum-data: null

networks:
  bridgenet:
    name: bridgenet
