version: "3.5"
name: sora2-substrate

services:
  sora-alice:
    image: sora2/substrate-local
    container_name: bridge-sora-alice
    restart: always
    build:
      context: ..
      dockerfile: bridge-docker/Dockerfile.sora
    ports:
      - "9944:9944"
      - "9954:9954"
    command: ["framenode", 
        "--pruning", "archive",
        "--enable-offchain-indexing", "true",
        "-d", "/data", 
        "--alice", 
        "--port", "10000", 
        "--ws-port", "9944",
        "--rpc-port", "9954", 
        "--unsafe-ws-external",
        "--unsafe-rpc-external",
        "--rpc-cors", "all",
        "--chain", "docker-local", 
        "--execution", "wasm", 
        "--wasm-execution", "compiled"
      ]
    volumes:
      - sora-alice-data:/data
    networks:
      - bridgenet
    
volumes:
  sora-alice-data: null

networks:
  bridgenet:
    name: bridgenet
