version: "3.5"
name: sora2-substrate

services:
  register-substrate-bridge:
    image: sora2/substrate-local
    container_name: bridge-register-substrate-bridge
    build:
      context: ..
      dockerfile: bridge-docker/Dockerfile.sora
    environment:
      - RUST_LOG=info,relayer=debug
    depends_on:
      sora-alice:
        condition: service_started
    entrypoint: sh
    command: /register-bridge/register-bridge.sh
    volumes:
      - ./register-substrate-bridge:/register-bridge
    networks:
      - bridgenet

  relay-sora-parachain-1:
    image: sora2/substrate-local
    container_name: bridge-relay-sora-parachain-1
    restart: always
    build:
      context: ..
      dockerfile: bridge-docker/Dockerfile.sora
    environment:
      - RUST_LOG=info,relayer=debug
    depends_on:
      register-substrate-bridge:
        condition: service_completed_successfully
    command:
      [
        "relayer",
        "--substrate-url",
        "ws://bridge-sora-alice:9944",
        "--parachain-url",
        "ws://bridge-parachain-alice:9844",
        "bridge",
        "relay",
        "sora",
        "parachain",
        "trusted",
        "--signer",
        "//Relay-key//1"
      ]
    networks:
      - bridgenet

  relay-sora-parachain-2:
    image: sora2/substrate-local
    container_name: bridge-relay-sora-parachain-2
    restart: always
    build:
      context: ..
      dockerfile: bridge-docker/Dockerfile.sora
    environment:
      - RUST_LOG=info,relayer=debug
    depends_on:
      register-substrate-bridge:
        condition: service_completed_successfully
    command:
      [
        "relayer",
        "--substrate-url",
        "ws://bridge-sora-alice:9944",
        "--parachain-url",
        "ws://bridge-parachain-alice:9844",
        "bridge",
        "relay",
        "sora",
        "parachain",
        "trusted",
        "--signer",
        "//Relay-key//2"
      ]
    networks:
      - bridgenet

  relay-parachain-sora-1:
    image: sora2/substrate-local
    container_name: bridge-relay-parachain-sora-1
    restart: always
    build:
      context: ..
      dockerfile: bridge-docker/Dockerfile.sora
    environment:
      - RUST_LOG=info,relayer=debug
    depends_on:
      register-substrate-bridge:
        condition: service_completed_successfully
    command:
      [
        "relayer",
        "--substrate-url",
        "ws://bridge-sora-alice:9944",
        "--parachain-url",
        "ws://bridge-parachain-alice:9844",
        "bridge",
        "relay",
        "parachain",
        "sora",
        "trusted",
        "--signer",
        "//Relay-key//1"
      ]
    networks:
      - bridgenet

  relay-parachain-sora-2:
    image: sora2/substrate-local
    container_name: bridge-relay-parachain-sora-2
    restart: always
    build:
      context: ..
      dockerfile: bridge-docker/Dockerfile.sora
    environment:
      - RUST_LOG=info,relayer=debug
    depends_on:
      register-substrate-bridge:
        condition: service_completed_successfully
    command:
      [
        "relayer",
        "--substrate-url",
        "ws://bridge-sora-alice:9944",
        "--parachain-url",
        "ws://bridge-parachain-alice:9844",
        "bridge",
        "relay",
        "parachain",
        "sora",
        "trusted",
        "--signer",
        "//Relay-key//2"
      ]
    networks:
      - bridgenet

networks:
  bridgenet:
    name: bridgenet
