[profile.dev]
debug = false

[profile.release]
lto = true
opt-level = 's'

[profile.test]
debug = false

[unstable]
weak-dep-features = true

[env]
PARACHAIN_METADATA_BRANCH = "polkadot-v0.9.38" # 'develop' branch after merge
