[package]
authors = ["Polka Biome Ltd. <jihoon@tutanota.de>"]
license = "BSD-4-Clause"
homepage = "https://sora.org"
repository = "https://github.com/sora-xor/sora2-network"
description = "Referrals"
edition = "2021"
name = "referrals"
version = "1.1.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = [
    "derive",
] }
scale-info = { workspace = true, default-features = false, features = ["derive"] }
frame-benchmarking = { workspace = true, default-features = false, optional = true }
frame-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }
common = { path = "../../common", default-features = false }
hex-literal = { workspace = true, default-features = false, optional = true }
serde = { workspace = true, optional = true, features = ["derive"] }
sp-std = { workspace = true, default-features = false }
traits = { workspace = true, default-features = false, optional = true }

[dev-dependencies]
common = { path = "../../common", features = ["test"] }
pallet-balances = { workspace = true, default-features = false }
sp-core = { workspace = true, default-features = false }
sp-io = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }
tokens = { workspace = true }
currencies = { workspace = true }
permissions = { path = "../permissions" }
assets = { path = "../assets"}

[features]
default = ["std"]

runtime-benchmarks = [
    "frame-benchmarking",
    "frame-system/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
    "hex-literal",
    "traits",
]

std = [
    "codec/std",
    "assets/std",
    "scale-info/std",
    "frame-benchmarking/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-balances/std",
    "sp-std/std",
    "common/std",
]

try-runtime = ["frame-support/try-runtime"]
