[package]
authors = ['Evgeni Zhukov <zhukov@soramitsu.co.jp>']
description = 'Consensus accounts for DEX purposes'
edition = '2018'
homepage = 'https://github.com/soramitsu/SoraNeo-substrate'
license = 'Unlicense'
name = 'technical'
repository = 'https://github.com/soramitsu/SoraNeo-substrate'
version = '0.1.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.1", default-features = false, features = ["derive"] }
frame-benchmarking = { version = "2.0.0", default-features = false, optional = true }
frame-support = { version = "2.0.0", default-features = false }
frame-system = { version = "2.0.0", default-features = false }
sp-runtime = { version = "2.0.0", default-features = false }
sp-core = { version = "2.0.0", default-features = false }
common = { path = "../../common", default-features = false }
assets = { path = "../assets", default-features = false }
pallet-balances = { version = "2.0.0", default-features = false }
currencies = { version = "0.3.2", package = "orml-currencies", default-features = false }
orml-traits = { version = "0.3.2", package = "orml-traits", default-features = false }
twox-hash = { version = "1.5.0", default-features = false }
sp-std = { version = "2.0.0", default-features = false }
serde = { version = "1.0.101", optional = true, features = ["derive"] }
trading-pair = { path = "../trading-pair", default-features = false, optional = true }
permissions = { path = "../permissions", default-features = false, optional = true }

hex-literal = { version = "0.3.1", optional = true }

[dev-dependencies]
sp-core = { version = "2.0.0", default-features = false }
sp-io = { version = "2.0.0", default-features = false }
dex-manager = { path = "../dex-manager", default-features = false }
permissions = { path = "../permissions", default-features = false }
tokens = { version = "0.3.2", package = "orml-tokens", default-features = false }

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'common/std',
    'assets/std',
    'currencies/std',
    'pallet-balances/std',
    'twox-hash/std',
    'sp-core/std',
    'sp-std/std',
    'serde',
]
runtime-benchmarks = [
    "frame-benchmarking",
    "frame-system/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
    "trading-pair",
    "permissions",

    "hex-literal",
]
