[package]
name = 'framenode'
version = '0.1.0'
authors = ["Parity Technologies <admin@parity.io>"]
build = 'build.rs'
edition = '2018'

[[bin]]
name = 'framenode'
path = 'src/main.rs'

[dependencies]
derive_more = '0.15.0'
exit-future = '0.1.4'
futures = { version = "0.3.1", features = ["compat"] }
hex-literal = "0.3.1"
log = '0.4.8'
parking_lot = '0.9.0'
trie-root = '0.15.2'
codec = { package = 'parity-scale-codec', version = '1.3.1', features = ["derive"]}
structopt = "0.3.3"
ansi_term = "0.12.1"
serde = { version = "1.0.101", features = ["derive"] }
common = { path = "../common" }
jsonrpc-core = "15.0.0"
dex-api-rpc = { path = "../pallets/dex-api/rpc" }
dex-manager-rpc = { path = "../pallets/dex-manager/rpc" }
technical = {path = "../pallets/technical" }
permissions = {path = "../pallets/permissions" }
xor-fee = {path = "../pallets/xor-fee"}
faucet = { path = "../pallets/faucet" }
trading-pair-rpc = { path = "../pallets/trading-pair/rpc" }
assets-rpc = { path = "../pallets/assets/rpc" }
liquidity-proxy-rpc = { path = "../pallets/liquidity-proxy/rpc" }

# Parachain dependencies
framenode-runtime = { path = "../runtime" }

# Substrate dependencies
sp-runtime = { version = "2.0.0", default-features = false }
sp-io = { version = "2.0.0", default-features = false }
sp-api = { version = "2.0.0", default-features = false }
sp-block-builder = { version = "2.0.0", default-features = false }
sp-blockchain = { version = "2.0.0", default-features = false }
sp-core = { version = "2.0.0", default-features = false }
sp-inherents = { version = "2.0.0", default-features = false }
sp-consensus = { version = "0.8.0", default-features = false }
sc-consensus = { version = "0.8.0", default-features = false }
sc-consensus-slots = { version = "0.8.0", default-features = false }
sc-consensus-babe = { version = "0.8.0", default-features = false }
sp-consensus-babe = { version = "0.8.0", default-features = false }
sc-consensus-aura = { version = "0.8.0", default-features = false }
sp-consensus-aura = { version = "0.8.0", default-features = false }
sc-cli = { version = "0.8.0", default-features = false }
sc-client-api = { version = "2.0.0", default-features = false }
sc-executor = { version = "0.8.0", default-features = false }
sc-service = { version = "0.8.0", default-features = false }
sc-transaction-pool = { version = "2.0.0", default-features = false }
sp-transaction-pool = { version = "2.0.0", default-features = false }
sc-network = { version = "0.8.0", default-features = false }
sc-basic-authorship = { version = "0.8.0", default-features = false }
sc-rpc = { version = "2.0.0", default-features = false }
sc-rpc-api = { version = "0.8.0", default-features = false }
sp-timestamp = { version = "2.0.0", default-features = false }
sp-trie = { version = "2.0.0", default-features = false }
grandpa = { package = "sc-finality-grandpa", version = "0.8.0", default-features = false }
sp-finality-grandpa = { version = "2.0.0", default-features = false }
sc-informant = { version = "0.8.0", default-features = false }
sc-chain-spec = { version = "2.0.0", default-features = false }
frame-support = { version = "2.0.0", default-features = false }
pallet-transaction-payment-rpc = { git = "https://github.com/soramitsu/sora2-frame-pallets", default-features = false, branch = "selected-v2.0.0"}
frame-benchmarking = '2.0.0'
frame-benchmarking-cli = '2.0.0'
substrate-frame-rpc-system = { version = "2.0.0", default-features = false }


[build-dependencies]
substrate-build-script-utils = { version = "2.0.0", default-features = false }

[dev-dependencies]
assert_cmd = "0.12"
nix = "0.17"
rand = "0.7.3"
tokio = { version = "0.2.13", features = ["macros"] }

# Substrate dependencies
pallet-sudo = { version = "2.0.0", default-features = false }
