[package]
authors = ["Polka Biome Ltd. <jihoon@tutanota.de>"]
license = "BSD-4-Clause"
homepage = "https://sora.org"
repository = "https://github.com/sora-xor/sora2-network"
description = "Polkaswap pallet for defining permissions model."
edition = "2021"
name = "permissions"
version = "1.1.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = [
    "derive",
] }
common = { path = "../../common", default-features = false }
scale-info = { workspace = true, default-features = false, features = ["derive"] }
frame-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }
serde = { workspace = true, features = ["derive"], default-features = false }
sp-core = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }

[dev-dependencies]
sp-io = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }
pallet-balances = { workspace = true }

[features]
default = ["std"]
std = [
    "codec/std",
    "common/std",
    "scale-info/std",
    "frame-support/std",
    "frame-system/std",
    "serde/std",
    "sp-core/std",
    "sp-std/std",
]

test = [
    "common/test"
]

try-runtime = [
    "frame-support/try-runtime",
]
