[package]
name = "common"
version = "0.1.0"
authors = ["Vladislav Markushin <negigic@gmail.com>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.1", default-features = false, features = ["derive"] }
serde = { version = "1.0", optional = true }
static_assertions = "1.1.0"
rustc-hex = { version = "2.1.0", default-features = false }
smallvec = "1.5.0"
blake2-rfc = { version = "0.2.18", default-features = false }
num-traits = { version = "0.2.12", default-features = false }
frame-support = { version = "2.0.0", default-features = false }
frame-system = { version = "2.0.0", default-features = false }
sp-arithmetic = { version = "2.0.0", default-features = false }
sp-core = { version = "2.0.0", default-features = false }
sp-runtime = { version = "2.0.0", default-features = false }
sp-std = { version = "2.0.0", default-features = false }
currencies = { version = "0.3.2", package = "orml-currencies", default-features = false }
orml-traits = { version = "0.3.2", package = "orml-traits", default-features = false }

[dev-dependencies]
serde_json = "1.0.41"

[features]
default = ['std']
std = [
    'codec/std',
    'serde',
    'rustc-hex/std',
    'blake2-rfc/std',
    'num-traits/std',
    'frame-support/std',
    'frame-system/std',
    'sp-arithmetic/std',
    'sp-core/std',
    'sp-runtime/std',
    'sp-std/std',
    'currencies/std',
    'orml-traits/std',
]
