[package]
name = "get-lp-tokens"
version = "0.1.0"
authors = ["Alexey Kalita <kalita.alexey@outlook.com>"]
edition = "2021"

[workspace]

[dependencies]
fixnum = { git = "https://github.com/sora-xor/fixnum", default-features = false, branch = "sora-v2.1.0", features = [
    "i128",
] }
reqwest = { version = "0.11.2", features = ["blocking", "json"] }
serde = { version = "1.0.125", features = ["derive"] }
