[package]
name = "get-lp-tokens"
version = "0.1.0"
authors = ["Alexey Kalita <kalita.alexey@outlook.com>"]
edition = "2021"

[workspace]

[dependencies]
fixnum = { workspace = true, default-features = false, features = [
    "i128",
] }
reqwest = { version = "0.11.2", features = ["blocking", "json"] }
serde = { version = "1.0.125", features = ["derive"] }
