[package]
authors = ['Polka Biome Ltd. <jihoon@tutanota.de>']
license = "BSD-4-Clause"
homepage = 'https://sora.org'
repository = 'https://github.com/sora-xor/sora2-network'
description = 'Pool XYK'
edition = '2021'
name = 'pool-xyk'
version = '1.2.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = [
    "derive",
] }
log = { workspace = true }
scale-info = { workspace = true, default-features = false, features = ["derive"] }
currencies = { workspace = true, default-features = false }
frame-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }
orml-traits = { workspace = true, default-features = false }
tokens = { workspace = true, default-features = false }
sp-core = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }
pallet-timestamp = { workspace = true, default-features = false }

ceres-liquidity-locker = { path = "../ceres-liquidity-locker", default-features = false }
common = { path = "../../common", default-features = false }
demeter-farming-platform = { path = "../demeter-farming-platform", default-features = false }
dex-manager = { path = "../dex-manager", default-features = false }
permissions = { path = "../permissions", default-features = false }
technical = { path = "../technical", default-features = false }
trading-pair = { path = "../trading-pair", default-features = false }

[dev-dependencies]
hex-literal = { workspace = true }
pallet-balances = { workspace = true, default-features = false }
sp-io = { workspace = true, default-features = false }
common = { path = "../../common", features = ["test"] }
dex-manager = { path = "../dex-manager" }
permissions = { path = "../permissions" }
pswap-distribution = { path = "../pswap-distribution" }
technical = { path = "../technical" }
trading-pair = { path = "../trading-pair" }
price-tools = { path = "../price-tools" }
xst = { path = "../xst" }
oracle-proxy = { path = "../oracle-proxy" }
band = { path = "../band" }
assets = { path = "../assets" }
extended-assets = { path = "../extended-assets", features = ["test"] }

[features]
default = ['std']

std = [
    'codec/std',
    "scale-info/std",
    "common/std",
    'currencies/std',
    'frame-support/std',
    'frame-system/std',
    'sp-core/std',
    'pallet-timestamp/std',
    'sp-runtime/std',
    'orml-traits/std',
    'tokens/std',
    'sp-runtime/std',
    'sp-std/std',
]

try-runtime = ["frame-support/try-runtime"]
