[package]
authors = ['Polka Biome Ltd. <jihoon@tutanota.de>']
license = "BSD-4-Clause"
homepage = 'https://sora.org'
repository = 'https://github.com/sora-xor/sora2-network'
description = 'Pool XYK'
edition = '2021'
name = 'pool-xyk'
version = '1.2.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = [
    "derive",
] }
scale-info = { version = "2", default-features = false, features = ["derive"] }
currencies = { git = "https://github.com/open-web3-stack/open-runtime-module-library.git", package = "orml-currencies", default-features = false }
frame-support = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
frame-system = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
num-traits = { version = "0.2.12", default-features = false }
orml-traits = { git = "https://github.com/open-web3-stack/open-runtime-module-library.git", package = "orml-traits", default-features = false }
orml-tokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library.git", package = "orml-tokens", default-features = false }
serde = { version = "1.0.101", optional = true, features = [
    "derive",
], default-features = false }
sp-core = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
sp-runtime = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
sp-std = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
pallet-timestamp = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }

assets = { path = "../assets", default-features = false }
ceres-liquidity-locker = { path = "../ceres-liquidity-locker", default-features = false }
common = { path = "../../common", default-features = false }
demeter-farming-platform = { path = "../demeter-farming-platform", default-features = false }
dex-manager = { path = "../dex-manager", default-features = false }
permissions = { path = "../permissions", default-features = false }
technical = { path = "../technical", default-features = false }
trading-pair = { path = "../trading-pair", default-features = false }

[dev-dependencies]
hex-literal = "0.4.1"
pallet-balances = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
sp-io = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.38", default-features = false }
common = { path = "../../common", features = ["test"] }
dex-manager = { path = "../dex-manager" }
permissions = { path = "../permissions" }
pswap-distribution = { path = "../pswap-distribution" }
technical = { path = "../technical" }
trading-pair = { path = "../trading-pair" }
price-tools = { path = "../price-tools" }
xst = { path = "../xst" }
oracle-proxy = { path = "../oracle-proxy" }
band = { path = "../band" }

[features]
default = ['std']

std = [
    'codec/std',
    "scale-info/std",
    'currencies/std',
    'frame-support/std',
    'frame-system/std',
    'num-traits/std',
    'serde/std',
    'sp-core/std',
    'sp-std/std',
]

try-runtime = ["frame-support/try-runtime"]
