[package]
name = "order-book"
authors = ["Soramitsu"]
license = "BSD-4-Clause"
homepage = "https://sora.org"
repository = 'https://github.com/sora-xor/sora2-network'
edition = "2021"
version = "0.1.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = [
    "derive",
] }
scale-info = { version = "2", default-features = false, features = ["derive"] }
sp-runtime = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }
sp-tracing = { workspace = true, default-features = false }
frame-benchmarking = { workspace = true, default-features = false, optional = true }
frame-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }
assets = { path = "../assets", default-features = false }
common = { path = "../../common", default-features = false }
technical = { path = "../technical", default-features = false }
trading-pair = { path = "../trading-pair", default-features = false }
hex-literal = "0.4.1"
serde = { version = "1.0", features = [
    "derive",
], optional = true, default-features = false }
tokens = { workspace = true, default-features = false }

[dev-dependencies]
sp-core = { workspace = true, default-features = false }
sp-io = { workspace = true, default-features = false }
framenode-chain-spec = { path = "../../node/chain_spec", features = ["test"] }
framenode-runtime = { path = "../../runtime", default-features = false, features = ["std", "test"] }
pallet-balances = { workspace = true }
pallet-collective = { workspace = true, default-features = false }
pallet-timestamp = { workspace = true, default-features = false }

[features]
default = ["std"]
std = [
    "common/std",
    "codec/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-timestamp/std",
    "scale-info/std",
    "serde",
    "sp-runtime/std",
    "sp-std/std",
    "technical/std",
    "trading-pair/std",
]

runtime-benchmarks = [
    "frame-system/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
    "pallet-collective/runtime-benchmarks",
    "framenode-runtime/runtime-benchmarks"
]

try-runtime = ["frame-support/try-runtime"]

private-net = [
     "framenode-chain-spec/private-net",
     "framenode-runtime/private-net",
]

test = []

wip = [
    "framenode-chain-spec/wip",
    "framenode-runtime/wip"
]
