[package]
name = "liquidity-proxy-rpc"
version = "0.1.0"
edition = "2021"
authors = ['Polka Biome Ltd. <jihoon@tutanota.de>']
license = "BSD-4-Clause"
homepage = 'https://sora.org'
repository = 'https://github.com/sora-xor/sora2-network'

[dependencies]
codec = { package = "parity-scale-codec", version = "3" }
jsonrpsee = { version = "0.16.2", features = ["server", "macros"] }
sp-runtime = { workspace = true }
sp-api = { workspace = true }
sp-blockchain = { workspace = true }
sp-std = { workspace = true }
sp-core = { workspace = true }
sp-rpc = { workspace = true }
liquidity-proxy-runtime-api = { path = "../runtime-api" }
common = { path = "../../../common" }

[features]
wip = ["liquidity-proxy-runtime-api/wip"]
