[package]
name = "oracle-proxy-rpc"
version = "1.0.0"
edition = "2021"
authors = ['Polka Biome Ltd. <jihoon@tutanota.de>']
license = "BSD-4-Clause"
homepage = 'https://sora.org'
repository = 'https://github.com/sora-xor/sora2-network'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oracle-proxy-runtime-api = { path = "../runtime-api" }
codec = { package = "parity-scale-codec", version = "3" }
jsonrpsee = { workspace = true, features = ["server", "macros"] }
sp-runtime = { workspace = true, default-features = false }
sp-blockchain = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }
sp-api = { workspace = true, default-features = false }
