[package]
edition = "2021"
name = "xst-benchmarking"
version = "0.1.0"
authors = ["Polka Biome Ltd. <jihoon@tutanota.de>"]
license = "BSD-4-Clause"
homepage = "https://sora.org"
repository = "https://github.com/sora-xor/sora2-network"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
currencies = { git = "https://github.com/open-web3-stack/open-runtime-module-library.git", package = "orml-currencies", default-features = false }
frame-support = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.25", default-features = false  }
frame-system = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.25", default-features = false  }
frame-benchmarking = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.25", default-features = false  }
hex-literal = { version = "0.3.1" }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.25", default-features = false  }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.25", default-features = false  }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.25", default-features = false }
common = { path = "../../../common", default-features = false  }
permissions = { path = "../../permissions", default-features = false  }
dex-manager = { path = "../../dex-manager", default-features = false  }
mock-liquidity-source = { path = "../../mock-liquidity-source", default-features = false  }
technical = { path = "../../technical", default-features = false  }
trading-pair = { path = "../../trading-pair", default-features = false  }
band = { path = "../../band", default-features = false  }
xst = {path = "../../xst", default-features = false  }

[features]
default = ["std"]
std = [
    "currencies/std",
    "frame-support/std",
    "frame-system/std",
    "frame-benchmarking/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-std/std",
    "common/std",
    "permissions/std",
    "dex-manager/std",
    "mock-liquidity-source/std",
    "technical/std",
    "trading-pair/std",
    "band/std",
    "xst/std",
]
