[package]
name = "generate-bags"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true, features = ["derive"] }

sp-io = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
frame-election-provider-support = { workspace = true }
pallet-staking = { workspace = true }

chrono = { workspace = true }
num-format = { workspace = true }

framenode-runtime = { path = "../../runtime", default-features = false, features = [
    "std",
] }
