[package]
name = "generate-bags"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1", features = ["derive"] }

sp-io = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.31" }
frame-support = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.31" }
frame-system = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.31" }
frame-election-provider-support = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.31" }
pallet-staking = { git = "https://github.com/sora-xor/substrate.git", branch = "polkadot-v0.9.31" }

chrono = { version = "0.4.19" }
git2 = { version = "0.13.25", default-features = false }
num-format = { version = "0.4.0" }

framenode-runtime = { path = "../../runtime", default-features = false, features = [
    "std",
] }
