[package]
edition = '2021'
authors = ['Polka Biome Ltd. <jihoon@tutanota.de>']
license = "BSD-4-Clause"
homepage = 'https://sora.org'
repository = 'https://github.com/sora-xor/sora2-network'
name = 'vested-rewards'
version = '1.2.1'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = [
    "derive",
] }
log = { version = "0.4.20" }
scale-info = { version = "2", default-features = false, features = ["derive"] }
currencies = { workspace = true, default-features = false }
frame-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }
frame-benchmarking = { workspace = true, default-features = false, optional = true }
hex-literal = { version = "0.4.1" }
serde = { version = "1.0.101", features = ["derive"], default-features = false }
sp-core = { workspace = true, default-features = false }
sp-io = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }
tokens = { workspace = true, default-features = false }
traits = { workspace = true, default-features = false }
common = { path = "../../common", default-features = false }
dex-manager = { path = "../dex-manager", default-features = false }
sp-runtime = { workspace = true, default-features = false }
hex = { version = "0.4", default-features = false, features = ["serde"] }
multicollateral-bonding-curve-pool = { path = "../multicollateral-bonding-curve-pool", default-features = false }
serde_bytes = { version = "0.11", default-features = false, features = [
    "alloc",
] }
serde_json = { version = "1.0", default-features = false }
technical = { path = "../technical", default-features = false }
pallet-timestamp = { workspace = true, default-features = false }
itertools = { version = "0.10.5", default-features = false }

[dev-dependencies]
pallet-balances = { workspace = true }
assets = { path = "../assets" }
common = { path = "../../common", features = ["test"] }
ceres-liquidity-locker = { path = "../ceres-liquidity-locker", default-features = false }
demeter-farming-platform = { path = "../demeter-farming-platform", default-features = false }
dex-manager = { path = "../dex-manager" }
permissions = { path = "../permissions" }
pool-xyk = { path = "../pool-xyk" }
pswap-distribution = { path = "../pswap-distribution" }
technical = { path = "../technical" }

[features]
default = ['std']
std = [
    'codec/std',
    "scale-info/std",
    'currencies/std',
    'frame-support/std',
    'frame-system/std',
    'hex/std',
    'multicollateral-bonding-curve-pool/std',
    'serde/std',
    'serde_bytes/std',
    'serde_json/std',
    'sp-core/std',
    'sp-io/std',
    'sp-runtime/std',
    'sp-std/std',
    'tokens/std',
    'traits/std',
]
runtime-benchmarks = [
    "frame-benchmarking",
    "frame-system/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
]
private-net = []

try-runtime = ["frame-support/try-runtime"]
