[package]
name = "kensetsu"
version = "0.0.1"
description = "Kensetsu pallet"
edition = "2021"
license = "BSD-4-Clause"
homepage = 'https://sora.org'
repository = 'https://github.com/sora-xor/sora2-network'
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
assets = { path = "../assets", default-features = false }
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = [
	"derive",
] }
log = { version = "0.4.20" }
common = { path = "../../common", default-features = false }
frame-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }
hex-literal = { version = "0.4", optional = true }
pallet-timestamp = { workspace = true, default-features = false }
scale-info = { version = "2", default-features = false, features = ["derive"] }
permissions = { path = "../permissions", default-features = false }
sp-arithmetic = { workspace = true, default-features = false }
sp-core = { workspace = true, default-features = false }
sp-io = { workspace = true, optional = true }
sp-runtime = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }
technical = { path = "../technical", default-features = false }

[dev-dependencies]
common = { path = "../../common", features = ["test"] }
currencies = { workspace = true }
pallet-balances = { workspace = true }
permissions = { path = "../permissions" }
hex-literal = "0.4"
# sp-io = { workspace = true }
sp-io = { workspace = true}
tokens = { workspace = true, default-features = false }

[features]
default = ["std"]
std = [
	"assets/std",
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"permissions/std",
	"sp-std/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-arithmetic/std",
	"scale-info/std",
	"technical/std",
]
try-runtime = ["frame-support/try-runtime"]
